name: Build web
on:
  push:
    branches:
      - dev
      - master
      - main
      - own
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          npm run build-gh-pages
          cp dist/index.html dist/404.html
      - name: Generate SEO files
        run: |
          node scripts/seo-generate.cjs
        continue-on-error: true
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
